### ISSUE TITLE
Tracking: Sprint #1

### ISSUE THREAD

**Issue by m-005** [xmtp/libxmtp#103]
Encapsulates:

Any infrastructure setup work that needs to happen
Any derisking work that needs to happen
All of the initialization logic that happens on startup (client.create())
Demo output:

New account flow/signatures
New account exists on the network
Private keys exist in local storage

```[tasklist]
### Account setup and infrastructure
- [ ] https://github.com/xmtp/xmtp-js/issues/347
- [ ] https://github.com/xmtp/xmtp-js/issues/349
- [ ] https://github.com/xmtp/xmtp-js/issues/345
- [ ] https://github.com/xmtp/xmtp-js/issues/352
- [ ] https://github.com/xmtp/xmtp-js/issues/346
- [ ] https://github.com/xmtp/proto/issues/81
- [ ] https://github.com/xmtp/xmtp-js/issues/350
- [ ] https://github.com/xmtp/libxmtp/issues/73
- [ ] https://github.com/xmtp/libxmtp/issues/74
- [ ] https://github.com/xmtp/libxmtp/issues/76
- [ ] https://github.com/xmtp/xmtp-js/issues/346
- [ ] https://github.com/xmtp/xmtp-js/issues/351
- [ ] https://github.com/xmtp/xmtp-js/issues/348
- [ ] https://github.com/xmtp/xmtp-js/issues/341
```

Encapsulates:

The steps required to initiate a conversation, loosely corresponding to conversations.newConversation() and conversation.send() in the JS API
Demo output:

```[tasklist]
### Conversation initiation
- [ ] https://github.com/xmtp/libxmtp/issues/78
- [ ] https://github.com/xmtp/libxmtp/issues/79
- [ ] https://github.com/xmtp/libxmtp/issues/80
```

**Comment by m-005** [comment]
@richardhuaaa consolidated #75 and #77 into this one sprint doc that we can keep track of progress for this sprint ending next Tuesday
