### ISSUE TITLE
Refactor Identity Updates to better support SCWs

### ISSUE THREAD

**Issue by neekolas** [xmtp/libxmtp#1033]
To verify a SCW signature, we need to be able to call out to external APIs (either the blockchain itself or a wrapper API we provide). This requires a certain amount of configuration.

In reviewing our code for the security audit, I realized that SCW signatures still contain the `chain_rpc_url` on the signature payload that goes over the wire and is then used by the recipient to verify the signature. That's a big no-no and needs to be fixed. That kind of configuration should be done at the app level. Otherwise someone could make a fake RPC that returns true for invalid signatures.

The problem is that the way we structure the code makes it very difficult to pass in some sort of `ScwValidator` struct at the time it's needed, and you end up having to plumb it through 6 different layers of code.

I think there is a better way. I propose we refactor the way we deserialize `IdentityUpdates` to handle signature verification as a separate step before we do all the other validations on an `IdentityUpdate`. This should lead to much cleaner code, since the `IdentityUpdate` object won't need to have all the `Box<dyn Signature>` signatures, and it can just take some sort of `ValidatedSignature` struct. If signature validation is handled separately it also makes it much easier to batch SCW signature validations and have many of them happen in parallel instead of serially. This will be a big deal if SCWs become standard issue in Converse and Coinbase Wallet (which feels like more a question of "when" than "if"). SCW signature verifications are _slow_ since they have to talk to blockchain nodes.

```[tasklist]
### Tasks
- [ ] https://github.com/xmtp/libxmtp/issues/1036
- [ ] https://github.com/xmtp/libxmtp/issues/1037
- [ ] https://github.com/xmtp/libxmtp/issues/1040
- [x] Allow for converting `UnverifiedIdentityUpdate`s into `IdentityUpdate`s
- [x] Refactor `IdentityUpdate` to take `ValidatedSignature` instead of `Box<dyn Signature>`
- [x] Make `get_state` and `apply_update` synchronous, since we will have removed all async code
- [x] Update `SignatureRequestBuilder` to work with new types
- [x] Add a bunch of test cases to make sure everything still behaves correctly
```
