### ISSUE TITLE
Audit findings tracking issue

### ISSUE THREAD

**Issue by neekolas** [xmtp/libxmtp#1185]
This is a tracking issue for all the actionable findings from the audit of `libxmtp`

Each issue should be fixed in a separate PR and linked to the appropriate ticket to make re-review easier.

```[tasklist]
### Tasks
- [ ] Update XIP-46 to specify that installation keys can authorize adding associated wallet addresses
- [ ] https://github.com/xmtp/libxmtp/issues/1186
- [ ] https://github.com/xmtp/libxmtp/issues/1187
- [ ] https://github.com/xmtp/libxmtp/issues/1188
- [ ] https://github.com/xmtp/libxmtp/issues/1189
- [ ] https://github.com/xmtp/libxmtp/issues/1190
- [ ] https://github.com/xmtp/libxmtp/issues/1191
- [ ] https://github.com/xmtp/libxmtp/issues/1192
- [ ] Clarify recovery address as a member role in XIP-46
- [ ] https://github.com/xmtp/libxmtp/issues/1184
```

**Comment by nplasterer** [comment]
Sorry @neekolas moving this to the done column of our tracker closes it. But all items from the code side should be completed so I think it's fine to keep this closed.
