### ISSUE TITLE
Forked Groups Tracking

### ISSUE THREAD

**Issue by insipx** [xmtp/libxmtp#1255]
Possible to-investigate:
- [ ] Set local to published and network publish fails
- [ ] if hit wrong epoch, we keep trying to process messages
- [ ] check pagination order in `query_group_messages`
- [ ] rely on local group_id from `MlsGroup` instead of the decrypted message in `process_external_message`
- [ ] Err(AlreadyProcessed) `process_for_id` how know processed?
- [ ] Order of messages/Wrong Epoch
    - [ ] when wrong epoch hit, want to get the previous pagination, until we hit the right epoch. Once we hit right epoch, re-start processing, and go to next page in message history
    - [ ] If message order is correct
- [ ] Cursor Issue: How can we get later epoch, i.e how to get epoch 25 before epoch 12?
