### ISSUE TITLE
[Tracking] Performance & Stability

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#1315]
```[tasklist]
### Tasks
- [ ] Test: for adding & removing members adds and removes all installations for that member
- [ ] Test: My other installations should add me new installation to groups
- [ ] Test: Revoking all other installations those installations can no longer see messages
- [ ] Test: Publishing two intents gets rejected by all including original intent
- [ ] Test: Tests that reproduce real app use cases 
- [ ] Test: Local state does not get corrupted on network loss
- [ ] Test: When hitting a wrong epoch sync restarts and retries intent
- [ ] Test: Group sync fetches all messages from the network since the last sync irregardless of streaming
- [ ] Test: When I send a message offline it will send on the next sync
- [ ] Test: Optimistically sending the message irregardless of current state retries 3 times and eventually sends the message
- [ ] Test: The main sync group is the latest sync group for all installations
- [ ] Improvement: Add datadog metrics for v3 functionality
- [ ] Improvement: Add alerting when a sync group is detected
- [ ] Improvement: Sync group should be created irregardless of if a history sync url is present
- [ ] Improvement: SyncAll should sync all group messages and welcomes
- [ ] Improvement: Remove sync on message send
- [ ] Improvement: Detect sdk versions for future breaking changes
```
