### ISSUE TITLE
[Tracking] Developer Experience

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#1332]
### Tasks
- [ ] [Android] Full Inbox example app with push notifications and wallet login
- [ ] [Android] Code Comment audit and additions
- [ ] [Android] Test suite running CI
- [ ] [iOS] Full Inbox example app with push notifications and wallet login
- [ ] [iOS] Test suite running CI
- [ ] [iOS] CI documentation code page
- [ ] [iOS] Code Comment audit and additions
- [ ] [RN] Full Inbox example app with push notifications and wallet login
- [ ] [RN] Test suite running CI
- [ ] [RN] Code Comment audit and additions
- [ ] [Web] Full Inbox example app with push notifications and wallet login
- [ ] [Web] Code Comment audit and additions
- [ ] [libXMTP] Code Comment audit and additions
- [ ] Documentation code samples
- [ ] https://github.com/xmtp/xmtp-react-native/issues/551
