### ISSUE TITLE
Tracking - Queryable Content Types in Rust

### ISSUE THREAD

**Issue by cameronvoell** [xmtp/libxmtp#1403]
### Is your feature request related to a problem?

- [ ] Move Content Types to new crate
- [ ] Start saving content type to DB
- [ ] Enable Readable only flag on messages FFI functions
- [ ] Add new Reaction Content Type with Reaction proto
- [ ] Add Legacy JSON deserialization for Reaction Content Type
- [ ] Extract queryable content field "parent_msg_id" from message and save to new db field parent id.
- [ ] Add query for returning "child_messages" when returning messages from a group
- [ ] Add messagesWithMetadata funciton to bindings_ffi configuring which metadata you want to return (initial option is reactions)

- [ ] Add Replies support for messagesWithMetadata function
- [ ] Add Read Receipt support for messagesWithMetadata function
- [ ] Move Remote Attachment Download and Decrypt logic to rust
