### ISSUE TITLE
Consent for allow/blocking of groups

### ISSUE THREAD

**Issue by neekolas** [xmtp/libxmtp#510]
We want to add support for allow/block actions on groups

This should mirror the existing consent work in the platform SDKs, but with new methods for `allowGroup` and `blockGroup` available. The actions should allow specifying `group_id` instead of `wallet_address`.

```[tasklist]
### Tasks
- [x] Update proto repo to have AllowGroup and BlockGroup actions available https://github.com/xmtp/proto/blob/main/proto/message_contents/private_preferences.proto
- [x] iOS SDK support for reading and writing to this new preference
- [x] Android SDK support for reading and writing to this new preference
- [x] RN Support wrapping the iOS and Android actions
```

**Comment by tuddman** [comment]
[PR for 1st task](https://github.com/xmtp/proto/pull/146)

**Comment by tuddman** [comment]
[PR for Android](https://github.com/xmtp/xmtp-android/pull/180)

**Comment by tuddman** [comment]
[PR for IOS](https://github.com/xmtp/xmtp-ios/pull/272)

**Comment by tuddman** [comment]
[PR for RN](https://github.com/xmtp/xmtp-react-native/pull/311)
