### ISSUE TITLE
Push notifications handling guide

### ISSUE THREAD

**Issue by neekolas** [xmtp/libxmtp#527]
We need to provide some resources for devs around push notification handling. We also need to expose methods for actually taking in the push notifications when they are received by the notification extension.

## Topics

Welcome topics have the format:
```ts
`/xmtp/mls/1/w-${hexEncode(installationId)}/proto`
```

Group message topics have the format:
```ts
`/xmtp/mls/1/g-${hexEncode(groupId)}/proto`
```

Clients should listen to these topics and then decode the payloads.

## Payload types
 
- Welcome messages are protobuf messages encoded with [`mlsv1.WelcomeMessage`](https://github.com/xmtp/proto/blob/main/proto/mls/api/v1/mls.proto#L115)
- Group messages are protobuf messages encoded with [`mlsv1.GroupMessage`](https://github.com/xmtp/proto/blob/main/proto/mls/api/v1/mls.proto#L145)

## What to do with messages
- Once payloads have been decoded from the push notification callers can pass them to `process_streamed_welcome_message` and `process_streamed_group_message` in our SDKs (these functions are not exposed outside of Rust).
```[tasklist]
### Tasks
- [x] Expose FFI interface for processing welcome and group messages to libxmtp
- [x] Add ability for callers to pass in Welcome messages to iOS SDK for processing
- [x] Add ability for callers to pass in Group messages to iOS SDK for processing
- [x] Add ability for callers to pass in Welcome messages to Android SDK for processing
- [x] Add ability for callers to pass in Group messages to Android SDK for processing
- [x] Add ability in RN
```

**Comment by nplasterer** [comment]
Would be nice to have a example running in RN for this but going to push this down in priority in favor of the HMAC work for now. PR started here: https://github.com/xmtp/xmtp-react-native/pull/347
