### ISSUE TITLE
Tracking: Group Chat - Prod (Mobile/LibXMTP)

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#549]
### **MUST**
  - [x] Push Notifications (SMALL) https://github.com/xmtp/libxmtp/issues/527 - @nplasterer 
  - [x] Enforce 250 limit (SMALL) https://github.com/xmtp/libxmtp/issues/503 - @alexrisch 
  - [x] Expose Message Kind (SMALL) https://github.com/xmtp/libxmtp/issues/522 - @nplasterer 
  - [x] Who added me in a group (SMALL) https://github.com/xmtp/libxmtp/issues/501 - @zombieobject 
  - [x] Message send state (SMALL) https://github.com/xmtp/libxmtp/issues/516 @nplasterer 
  - [x] Mutable Metadata (MEDIUM) https://github.com/xmtp/libxmtp/issues/548 - @cameronvoell 
  - [x] xmtp/libxmtp#651 - @nplasterer 
  - [x] https://github.com/xmtp/libxmtp/issues/732 - @nplasterer 
  - [x] Identity work - @nplasterer 
  - [x] xmtp/libxmtp#752  - @nplasterer 
  - [x] xmtp/libxmtp#650
  - [x] https://github.com/xmtp/libxmtp/issues/816 - @nplasterer 
  - [x] https://github.com/xmtp/libxmtp/issues/805 - @cameronvoell 
  - [x] xmtp/libxmtp#664 - @cameronvoell 
  - [x] xmtp/libxmtp#701 - @insipx 
  - [x] https://github.com/xmtp/libxmtp/issues/714 - @tuddman 

###  **SHOULD**
  - [ ] Message History (LARGE) https://github.com/xmtp/libxmtp/issues/619 - @tuddman *
  - [ ] https://github.com/xmtp/libxmtp/issues/504
  - [ ] https://github.com/xmtp/libxmtp/issues/671
  - [ ] xmtp/botkit#18 - @rygine 
  - [ ] Leave (self removal) (MEDIUM) https://github.com/xmtp/libxmtp/issues/441
  - [ ] Is Sender HMAC Verification (MEDIUM) https://github.com/xmtp/libxmtp/issues/422 *
  - [ ] Streaming Reliability
  
  * Becomes a must if multi clients launch

### **MUST**
- [ ] Key rotation after welcome (SMALL) https://github.com/xmtp/libxmtp/issues/347 - @lfzkoala 
- [x] https://github.com/xmtp/libxmtp/issues/678 - @nplasterer

###  **SHOULD**
- [ ] Key Package updates - https://github.com/xmtp/libxmtp/issues/366 https://github.com/xmtp/libxmtp/pull/541
  - [ ] Credential Validation (blocked on identity work)
  - [ ] Matching MLS spec https://www.rfc-editor.org/rfc/rfc9420.html#name-credential-validation
  - [ ] Matching identity doc
  - [ ] Not allowing credential updates/changes
- [ ] Security Audit
  
  
## BACKEND

- [ ] Datadog Metrics
- [ ] Dune Dashboards
- [x] Released on Production Network

## DOCS

- [x] Push Notifications Docs
- [x] SDK Integration Docs
- [x] Technical Docs
  - [x] Identity Docs

**Comment by nplasterer** [comment]
Production Ready Checklist

- [ ] Can make a change to mutable metadata without needing a database wipe (or with a clear migration path setup to do so) *Frames Link*
- [ ] Update MLS storage to be TLS serialization instead of json https://github.com/xmtp/libxmtp/issues/714
- [ ] Validate Performance 
- [ ] Thorough testing of features (inbox mobile being used to find bugs)
