### ISSUE TITLE
Tracking: WASM Bindings (Group Chat Prod - Web)

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#557]
### Must Have

- [ ] DB Storage layer (LARGE) ~https://github.com/xmtp/libxmtp/issues/556~ https://github.com/xmtp/libxmtp/issues/942
- [x] #563
- [ ] `bindings_wasm` that mirror `bindings_ffi` https://github.com/rustwasm/wasm-bindgen (XXL)
  - [x] Client
    - [x] #565 *Node
    - [x] #566 *Node
    - [x] #567 *Node
    - [x] #568 *Node
    - [x] #569 *Node
    - [x] #570
  - [x] Conversation
    - [x] #571
    - [x] #572
    - [x] #573 *Node
    - [x] #574 *Node
    - [x] #575 *Node
  - [x] Group
    - [x] #576 *Node
    - [x] #577 *Node
    - [x] #578
    - [x] #579
    - [x] #580
    - [x] #581
    - [x] #582 *Node
    - [x] #583
    - [x] #584 *Node
    - [x] #585
    - [x] #586
    - [x] #587
  - [ ] Reducing the binary size for libxmtp. We need to measure this and make sure it's not enormous, and prune/modularize/swap out dependencies if it is.

**Comment by bwcDvorak** [comment]
Github, your 'convert to item' did me dirty when it came to converting [issue 564](https://github.com/xmtp/libxmtp/issues/564), formerly a task about making the WASM bindings with a reference to an external URL. Apologies @nplasterer - can you please edit the correct title back into that issue?

**Comment by nplasterer** [comment]
@bwcDvorak I think that item is just a header and doesn't need to be an issue.

**Comment by insipx** [comment]
Wasm runtimes support Host Functions. This seems to be similar to this, where we would expose a rust trait that JS needs to implement and pass host functions into the generated WASM blob. These host functions would generally be `write`/`read` etc, whatever SQLite normally does in the rust code. Could be very close to the trait Cryspen made for OpenMLS. This would require a bit of work on the JS side, but it does circumvent the need for WASI, at least until its in a more stable state.

**Comment by neekolas** [comment]
The fact that `wasm_bindgen` supports really complicated browser APIs in `web-sys` (it can do things like use [WebGL](https://rustwasm.github.io/docs/wasm-bindgen/examples/webgl.html)) gives me hope that the host function support is pretty mature and full-featured.

**Comment by insipx** [comment]
@rygine correct me if i'm wrong, but I think everything on this list can be closed!

**Comment by rygine** [comment]
@insipx i think the only thing missing in the WASM bindings is streaming. should that be tracked separately?

**Comment by insipx** [comment]
right! yeah I'll add all the streaming to separate issue
