### ISSUE TITLE
Tracking: Message History

### ISSUE THREAD

**Issue by tuddman** [xmtp/libxmtp#619]
- [x] Implement & Test a round trip for Message backup Request -> Response.
- [x] Implement & Test that the request has the correct fields.
- [x] Implement & Test that the response has the correct fields.
- [x] Implement & Test that a `Sync` group is properly created.
- [x] Implement & Test the polling of whether a request has been broadcast out.
- [x] Implement & Test that the request & response message(s) are of a custom content type.
- [x] Implement & Test the request storage lifecycle - including verifying origination of the request.
- [x] Implement & Test the generated PIN storage + sending + verification
- [x] Implement & Test encryption of the message-bundle.
- [x] Implement & Test serialization of the message-bundle.
- [x] Implement & Test uploading of the message-bundle
- [x] Implement & Test downloading of the message-bundle
- [x] Implement & Test decryption of the message-bundle.
- [x] Implement & Test deserialization of the message-bundle
- [x] Implement & Test insertion/storage of the message-bundle
- [x] Make a diagram explaining the flow
- [x] Implement & Test message-bundle responder adding message-bundle requester to all groups
- [x] Implement & Test the validation rules that prevent non-allowed parties from joining a `Sync` group.
- [x] FFI bindings:  `client::new().with_sync_options(url)`, `allow_sync`, `send_history_request`
- [x] Stand up a default message history server with adequate storage backing.

**Comment by nplasterer** [comment]
Just wanted to add a little context from our chat last week about what will be required on the SDK/binding side.

- LIBXMTP Bindings
    - A function to initiate a request to upload messages
      - This uses a new topic to send a message with a pin for user validation
    - A function to trigger a upload of messages
- SDK
    - A new topic for message history (only for handling in push notification)
    - Subscribe functionality for these new topics (subscribeToBackupRequest)
      - This listens for the new topic messages and if validated triggers an upload of messages
    - Send new topic for this event (sendBackupRequest)
      - Triggered on new installation logins

**Comment by tuddman** [comment]
For anyone finding this tracking ticket: there is also [this companion repo](https://github.com/xmtp/xmtp-message-history-server) to handle the temporary storage and relaying of the message bundles.
