### ISSUE TITLE
Expose API in MLS Validation Service for processing identity updates

### ISSUE THREAD

**Issue by neekolas** [xmtp/libxmtp#622]
The MLS Validation Service must provide an API that takes in a list of `IdentityUpdates` and returns the final AssociationState (or a relevant error).
```[tasklist]
### Tasks
- [x] Update protos for MLS validation service to include new `GetAssociationState` method
- [x] Implement method to get a final AssociationState
- [x] Define Protobuf serialization for AssociationState
```
