### ISSUE TITLE
Implement signature verification for all known signature types

### ISSUE THREAD

**Issue by neekolas** [xmtp/libxmtp#636]
In [this PR](https://github.com/xmtp/libxmtp/pull/633/files#diff-89b6a0b4851dce77ffc6a6e49fbb747fbb5397d1948a36991c108087fb0ac684) we have a bunch of new signature types introduced, but the `recover_signer` method is stubbed out for all of them. 

We'll need real `recover_signer` methods for all signature types before we can have IdentityUpdate verification working end to end.

Feel free to update the struct and error types as-needed to make this happen.
```[tasklist]
### Tasks
- [ ] Move stuff that belongs to `xmtp_cryptography` to it
- [ ] working version
- [ ] remove xmtp_mls dependencies
- [ ] refactor `allowed_signature_for_kind` into xmtp_id::Signature
- [ ] CAIP-10 struct
```
