### ISSUE TITLE
Complete libxmtp migration

### ISSUE THREAD

**Issue by neekolas** [xmtp/libxmtp#707]
There are a ton of small tasks required to complete the migration of libxmtp to use `inbox_id`
```[tasklist]
### Tasks
- [ ] Update database models that reference account_address to use inbox_id
- [x] Update group permissions to use creator_inbox_id instead of account address
- [ ] Update add/remove members methods to resolve account addresses to inbox_ids
- [ ] https://github.com/xmtp/libxmtp/issues/715
- [ ] Figure out how to generate message id without account_address
- [ ] Update transcript messages to use inbox_id
- [ ] Update can_message to use new inbox functions
- [ ] Remove creator_account_address from group metadata
- [ ] Update added_by_address to added_by_inbox
- [ ] https://github.com/xmtp/libxmtp/issues/716
- [ ] https://github.com/xmtp/libxmtp/issues/717
- [ ] https://github.com/xmtp/libxmtp/issues/719
```
