### ISSUE TITLE
Tracking: Account setup and infrastructure

### ISSUE THREAD

**Issue by richardhuaaa** [xmtp/libxmtp#75]
Encapsulates:
- Any infrastructure setup work that needs to happen
- Any derisking work that needs to happen
- All of the initialization logic that happens on startup (client.create())

Demo output:
- New account flow/signatures
- New account exists on the network
- Private keys exist in local storage

```[tasklist]
### Tasks
- [ ] https://github.com/xmtp/xmtp-js/issues/347
- [ ] https://github.com/xmtp/xmtp-js/issues/349
- [ ] https://github.com/xmtp/xmtp-js/issues/350
- [ ] https://github.com/xmtp/proto/issues/81
- [ ] https://github.com/xmtp/libxmtp/issues/73
- [ ] https://github.com/xmtp/libxmtp/issues/74
- [ ] https://github.com/xmtp/xmtp-js/issues/348
- [ ] https://github.com/xmtp/xmtp-js/issues/351
- [ ] https://github.com/xmtp/xmtp-js/issues/341
- [ ] https://github.com/xmtp/xmtp-js/issues/345
- [ ] https://github.com/xmtp/xmtp-js/issues/352
- [ ] https://github.com/xmtp/xmtp-js/issues/346
- [ ] https://github.com/xmtp/libxmtp/issues/76
```
