### ISSUE TITLE
Tracking: Conversation initiation

### ISSUE THREAD

**Issue by richardhuaaa** [xmtp/libxmtp#77]
Encapsulates:
- The steps required to initiate a conversation, loosely corresponding to `conversations.newConversation()` and `conversation.send()` in the JS API

Demo output:

```[tasklist]
### Tasks
- [ ] https://github.com/xmtp/libxmtp/issues/78
- [ ] https://github.com/xmtp/libxmtp/issues/79
- [ ] https://github.com/xmtp/libxmtp/issues/80
```
