### ISSUE TITLE
Tracking: Smart Contract Wallets & Identity Followups

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#890]
### MVP
- [x] #869 
- [x] #891 - @nplasterer 
- [x] #892
- [x] #893
- [x] #895 - @nplasterer 
- [x] #894 - @nplasterer 
- [x] https://github.com/xmtp/libxmtp/issues/1070 - @codabrink 
- [ ] https://github.com/xmtp/xmtp-react-native/issues/510 - @Koleok 

### Follow ups
- [ ] https://github.com/xmtp/libxmtp/issues/744
- [ ] https://github.com/xmtp/libxmtp/issues/764
- [x] https://github.com/xmtp/libxmtp/issues/853
- [ ] https://github.com/orgs/xmtp/projects/11/views/3
