### ISSUE TITLE
Tracking: MLS/WASM DB Storage

### ISSUE THREAD

**Issue by insipx** [xmtp/libxmtp#942]
- [x] #938 
- [x] #939
- [x] #940
- [x] #941
    - [x] https://github.com/xmtp/libxmtp/issues/1038
    - [x] #1034 
- [x] #951
- [x] #952 
- [x] embed migrations
- [x] #1099
- [x] updated README for wasm backend crate (use/building/etc)
- [x] CI Workflow #1035 
- [ ] ~`diesel-wasm-sqlite` `0.1.0` crate release~ moved to its [own crate](https://github.com/xmtp/diesel-wasm-sqlite)

Future feature-parity work with C diesel backend:
- instrumentation
- allow `serialize`/`deserialize` database #1003 
    - `fn serialize_database_to_buffer`
    - `fn deserialize_readonly_database_from_buffer`
    - 
- custom function registration
    - `fn register_diesel_sql_functions` (currently only in JS bc of AsyncClosure difficulties)
    - `fn register_collation`
    - `fn register_aggregate_function`
    - `fn register_noarg_sql_function`
    - `fn register_sql_function`
